Models/ContactFormViewController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BCoTRestaurant.Models
{
    public class ContactFormViewModel
    {
        [Required]
        public string Name { get; set; }

        [Required, EmailAddressAttribute]
        public string Email { get; set; }

        [Phone]
        public string PhoneNumber { get; set; }

        [Required, DataType(DataType.DateTime)]
        public string DateTime { get; set; }

        [Required, Range(1, 20)]
        public string Diners { get; set; }

        [Required]
        public string Subject { get; set; }

        [Required]
        public string Message { get; set; }

        public string EmailRecipient { get; set; }

        public string CCRecipient { get; set; }

        [AllowHtml]
        public string AutoMessage { get; set; }
    }
}

Controllers/ContactFormSurfaceController.cs
using BCoTRestaurant.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace BCoTRestaurant.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {
        // GET: ContactFormSurface
        public ActionResult Index()
        {
            return PartialView("ContactForm", new ContactFormViewModel());
        }

        [HttpPost]
        public ActionResult HandleFormSubmit(ContactFormViewModel model)
        {
            if (!ModelState.IsValid)
                return CurrentUmbracoPage();

            // send email
            string userMessage = string.Format("<div style='font-family: arial; font-size: 90%'>Tel: {0}<br />Number of diners: {1}<br />Date Time: {2}<br />{3}</div>", model.PhoneNumber, model.Diners, model.DateTime, model.Message);

            MailMessage message = new MailMessage();
            message.To.Add(model.EmailRecipient);

            if (model.CCRecipient != null)
            {
                message.To.Add(model.CCRecipient);
            }

            message.IsBodyHtml = true;
            message.Subject = model.Subject;
            message.From = new MailAddress(model.Email, model.Name);
            message.Body = userMessage;
            SmtpClient smtp = new SmtpClient();
            smtp.Send(message);

            // send automated email to user
            MailMessage autoMessage = new MailMessage();
            autoMessage.IsBodyHtml = true;
            autoMessage.To.Add(model.Email);
            autoMessage.Subject = String.Format("RE: {0}", model.Subject);
            autoMessage.From = new MailAddress("restaurant@bcot.ac.uk", "BCoT Restaurant");
            autoMessage.Body = model.AutoMessage;
            SmtpClient autoSmtp = new SmtpClient();
            autoSmtp.Send(autoMessage);

            TempData["success"] = true;

            return RedirectToCurrentUmbracoPage();
        }
    }
}

Views/Article.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.FolderArticles>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

@section header{
	@{
		UmbracoHelper umbracoHelper = new UmbracoHelper(UmbracoContext.Current);
		IPublishedContent content = umbracoHelper.TypedContentSingleAtXPath("//homepage");
		var vCSS = content.GetPropertyValue("cSSVersion");
	}
	
	<link rel="stylesheet" href="/css/BCoTArticle.css?v=@vCSS" />
}

<div class="container bcotarticle">

	<div class="row articleTitle">
		<h1>Do Not Use This Template</h1>
		<div class="col-md-12">@Umbraco.Field("pageName")</div>
			
		
	</div>
	<div>
		@CurrentPage.GetGridHtml("layout")
	</div>
			

</div>

Views/BCoTArticle.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.FolderArticles>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

@section header{
	@{
		UmbracoHelper umbracoHelper = new UmbracoHelper(UmbracoContext.Current);
		IPublishedContent content = umbracoHelper.TypedContentSingleAtXPath("//homepage");
		var vCSS = content.GetPropertyValue("cSSVersion");
	}
	
	<link rel="stylesheet" href="/css/BCoTArticle.css?v=@vCSS" />
}

<div class="container bcotarticle">

	<div class="row articleTitle">
		<div class="col-md-12">@Umbraco.Field("pageName")</div>
	</div>
	
	<div>
		@CurrentPage.GetGridHtml("layout")
	</div>
</div>

Views/BCoTArticleSidebar.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.FolderArticles>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

@section header{
	@{
		UmbracoHelper umbracoHelper = new UmbracoHelper(UmbracoContext.Current);
		IPublishedContent content = umbracoHelper.TypedContentSingleAtXPath("//homepage");
		var vCSS = content.GetPropertyValue("cSSVersion");
	}
	
	<link rel="stylesheet" href="/css/BCoTArticle.css?v=@vCSS" />
}

<div class="container bcotarticle">

	<div class="row articleTitle">
		<div class="col-md-12">@Umbraco.Field("pageName")</div>
	</div>
	
	<div class="row">
	
		<div class="col-md-9 articleMainContent">
			@CurrentPage.GetGridHtml("layout")
		</div>
		<div class="col-md-3 articleSideBar">
			This is the sidebar
		</div>
	</div>
</div>

Views/BookingPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.BookingPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

@section header{
	@{
		UmbracoHelper umbracoHelper = new UmbracoHelper(UmbracoContext.Current);
		IPublishedContent content = umbracoHelper.TypedContentSingleAtXPath("//homepage");
		var vCSS = content.GetPropertyValue("cSSVersion");
	}
	
	<link rel="stylesheet" href="/css/BCoTArticle.css?v=@vCSS" />
}

<div class="container bcotarticle">
	<div class="row articleTitle">
		<div class="col-xs-12">@Umbraco.Field("pageName")</div>
	</div>
	<div>
		<div class="col-md-4">
			<div id="resmio-the-restaurant-bcot"></div> 
			<script>(function(d, s) { var js, rjs = d.getElementsByTagName(s)[0]; js = d.createElement(s); js.src = "//static.resmio.com/static/en-gb/widget.js#id=the-restaurant-bcot&amp;width=275px&amp;height=400px"; rjs.parentNode.insertBefore(js, rjs); }(document, "script")); </script> 
			</div>
		<div class="col-md-8">
			@CurrentPage.GetGridHtml("layout")
		</div>
	</div>
	<!-- Don't think the Google map works here
	<div class="row">
		<div class="col-md-12">
			<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d9986.321090863552!2d-1.095904!3d51.263637!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xa185131bd75c903e!2sBCoT+-+Basingstoke+College+Of+Technology!5e0!3m2!1sen!2suk!4v1486125610941" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
		</div>
	</div>
	-->
</div>

Views/ContactPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ContactPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
@section header{
	@{
		UmbracoHelper umbracoHelper = new UmbracoHelper(UmbracoContext.Current);
		IPublishedContent content = umbracoHelper.TypedContentSingleAtXPath("//homepage");
		var vCSS = content.GetPropertyValue("cSSVersion");
	}
	
	<link rel="stylesheet" href="/css/contact.css?v=@vCSS" />
}
<div class="container contact">
	<div class="row contactTitle">
		@Umbraco.Field("pageName")
	</div>
	<div class="row">
		<div class="col-xs-12 col-md-6 col-md-offset-3">		
			@Html.Action("Index", "ContactFormSurface")
		</div>
	</div>
</div>

Views/Event.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Event>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}


@section header{
	@{
		UmbracoHelper umbracoHelper = new UmbracoHelper(UmbracoContext.Current);
		IPublishedContent content = umbracoHelper.TypedContentSingleAtXPath("//homepage");
		var vCSS = content.GetPropertyValue("cSSVersion");
	}
	
	<link rel="stylesheet" href="/css/event.css?v=@vCSS" />
}

<div class="container event">
	<div class="row eventTitle">
		<div class="col-xs-12" title="@Umbraco.Field("evt_summary")">@Umbraco.Field("pageName")</div>
	</div>
	
	<div class="row">
		<div class="col-xs-12 col-md-8">
			<p class="eventDate">@Convert.ToDateTime(@Umbraco.Field("evt_startDate").ToString()).ToString("dddd, dd MMMM yyyy")</p>
			<p class="eventDate">Start Time : @Convert.ToDateTime(@Umbraco.Field("evt_startDate").ToString()).ToString("HHmm")</p>
			@CurrentPage.GetGridHtml("evt_content")
		</div>
		<div class="col-xs-12 col-md-4">
			<p class="evtHeader">Forthcoming Events</p>

			@{
				@*
					// Another method to get content by ID
					UmbracoHelper umbracoHelper = new UmbracoHelper(UmbracoContext.Current);
					// Multiple nodes
					IEnumerable<IPublishedContent> content = umbracoHelper.TypedContentAtXPath("//news");
					// Single node
					IPublishedContent content = umbracoHelper.TypedContentSingleAtXPath("//" + alias);
				*@
				
				var lstEvents = CurrentPage.Site().Descendants("event").Where("visible").OrderBy("evt_startDate descending");
				
				@* Only get future events *@
				lstEvents = lstEvents.Where("evt_startDate >= @0", DateTime.Now).OrderBy("evt_startDate descending");
				
				foreach(var events in lstEvents)
				{
					DateTime dtEvents = Convert.ToDateTime(events.evt_startDate.ToString());
					<a class="evtLink" href="@events.Url">
						<p class="evtDate">@dtEvents.ToString("dddd, dd MMMM yyyy")</p>
						<p class="evtTitle">@events.Name</p>
						<p class="evtSummary">@events.evt_summary</p>
					</a>
					<hr />
				}
			}

		</div>
	</div>
</div>

Views/Gallery.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Gallery>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

@section header{
	@{
		UmbracoHelper umbracoHelper = new UmbracoHelper(UmbracoContext.Current);
		IPublishedContent content = umbracoHelper.TypedContentSingleAtXPath("//homepage");
		var vCSS = content.GetPropertyValue("cSSVersion");
	}
	
	<link rel="stylesheet" href="/css/gallery.css?v=@vCSS" />
}

<div class="container bcotGallery">
	<div class="row galleryTitle">
		<div class="col-md-12">@Umbraco.Field("title")</div>
	</div>
	
	<div class="row">
		<div class="col-md-12">@Umbraco.Field("description")</div>
	</div>
	
	<div class="row">
		<div id="photos">
		@{
			var lstGallery = CurrentPage.Children;
				
				foreach(var galleryImage in lstGallery)
				{
					@*<div class="col-md-4 galleryColumn">
						<a href="@galleryImage.destinationurl" title="@galleryImage.description">
							<img class="galleryImage" src="@Umbraco.Media(@galleryImage.image).Url" alt="@galleryImage.description" />
						</a>
						
						<p>@galleryImage.fullDescription</p>
					</div>*@
					<img class="galleryImage" src="@Umbraco.Media(@galleryImage.image).Url" alt="@galleryImage.description" />
				}
		}
	</div>

Views/Homepage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Homepage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";

	@* Build link boxes and its styles at the bottom of the homepage *@
	System.Text.StringBuilder sbLinkBoxes = new System.Text.StringBuilder();
	System.Text.StringBuilder sbLinkCSS = new System.Text.StringBuilder();
	
	sbLinkCSS.AppendLine("<style type=\"text/css\">");
	
	@* Only allow the first four link boxes *@
	var vLinkBoxes = CurrentPage.Site().Descendants("box").Where("visible").Take(4);
	var count = 1;

	foreach(var box in vLinkBoxes)
	{
		var vClass = String.Format("divSBox{0}", count);
		var vBackgroundImage = String.Empty;
		var vURL = box.boxExtURL;
		
		if(Umbraco.TypedMedia(box.boxImage) != null)
		{
			vBackgroundImage = Umbraco.TypedMedia(box.boxImage).Url;
		}

		@* Check if there's a content picked, if not, use the external URL *@
		if(!String.IsNullOrEmpty(box.boxURL))
		{
			vURL = box.boxURL;
		}
		
		@* Construct boxes *@
		sbLinkBoxes.AppendLine("	<div class=\"col-xs-12 col-md-3\">");
		sbLinkBoxes.AppendFormat("		<a href=\"{0}\" class=\"{1}\">", vURL, vClass).AppendLine();
		sbLinkBoxes.AppendFormat("			<h5>{0}</h5>", box.Name).AppendLine();
		sbLinkBoxes.AppendLine("		</a>");
		sbLinkBoxes.AppendLine("	</div>");
		
		@* Construct styles *@
		sbLinkCSS.AppendFormat("		a.divSBox{0}", count).AppendLine();
		sbLinkCSS.AppendLine("		{");
		sbLinkCSS.AppendFormat("			background: #{0} url(\"{1}\");", box.boxColor, vBackgroundImage).AppendLine();
		sbLinkCSS.AppendFormat("			color: #{0};", box.boxFontColor).AppendLine();
		sbLinkCSS.AppendLine("		}");

		count++;
	}
	
	sbLinkCSS.AppendLine("</style>");
}

@section header{
<!-- Content here -->
	@{
		UmbracoHelper umbracoHelper = new UmbracoHelper(UmbracoContext.Current);
		IPublishedContent content = umbracoHelper.TypedContentSingleAtXPath("//homepage");
		var vCSS = content.GetPropertyValue("cSSVersion");
	}
	
	<link rel="stylesheet" href="css/homepage.css?v=@vCSS" />
	
	<link rel="stylesheet" type="text/css" href="/slick/slick.css?v=@vCSS" />
	<!-- Add the new slick-theme.css if you want the default styling -->
	<link rel="stylesheet" type="text/css" href="/slick/slick-theme.css?v=@vCSS" />
	<link rel="stylesheet" type="text/css" href="/css/slick-custom.css?v=@vCSS" />
	
	@* Style sheet for navigations *@
	@Umbraco.RenderMacro("NaviCss")
	
	<script type="text/javascript">
		@* Create cookie *@
		function setCookie(cname, cvalue, exdays)
		{
			var d = new Date();
			d.setTime(d.getTime() + (exdays*24*60*60*1000));
			var expires = "expires = " + d.toGMTString();
			document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
		}

		@* Get cookie value *@
		function getCookie(cname)
		{
			var name = cname + "=";
			var decodedCookie = decodeURIComponent(document.cookie);
			var ca = decodedCookie.split(';');
			for(var i = 0; i < ca.length; i++)
			{
				var c = ca[i];
				while (c.charAt(0) == ' ')
				{
					c = c.substring(1);
				}
				if(c.indexOf(name) == 0)
				{
					return c.substring(name.length, c.length);
				}
			}
			return "";
		}
	</script>

	@Html.Raw(sbLinkCSS.ToString())
}

@*
	Insert this section at the bottom of master page, just after link to jQuery
	This is to display any popup message on page load
*@
@section afterjQuery{
	@if(@Umbraco.Field("modalEnable").ToString() == "True")
	{
		@* Check if the ID matches cookie ID *@
		var vID = @Umbraco.Field("modalID");
		
		<script type="text/javascript">
			$(document).ready(function(){
			
				@* check to see if the modal message should be set *@
				var user = getCookie("modalMessage");
				if(user == "" || user != "@vID")
				{
					$('#myModal').modal('show');

					@* Create cookie for popup message with 1 day expiration *@
					setCookie("modalMessage", @vID, 1);
				}
				
				
				@* now check for previously visitied departments *@
				var prevDept = getCookie("departmentHistory");
				var strSplit = prevDept.split(",");
				document.getElementById("favDept").innerHTML = strSplit[0].toString();
				document.getElementById("favLink").href=strSplit[2];
			});
		</script>
	}
	
	<script type="text/javascript" src="/slick/slick.min.js"></script>
	<script src="scripts/slickInitialise.js"></script>
}

@section modalMessage{
	@{
		UmbracoHelper umbracoHelper = new UmbracoHelper(UmbracoContext.Current);
		IPublishedContent content = umbracoHelper.TypedContentSingleAtXPath("//homepage");
	}
	@if(@content.ShowToVisitor())
	{
		<div class="modal fade in" id="myModal" tabindex="-1" role="dialog">
	  		<div class="modal-dialog" role="document">
		    	<div class="modal-content">
		      		<div class="modal-header">
		        		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        		<h4 class="modal-title">@Umbraco.Field("modalTitle")</h4>
		      		</div>
		    	  	<div class="modal-body">
			    	    <p>@Umbraco.Field("modalMessage")</p>
				    </div>
			    	<div class="modal-footer">
		    	    	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			      	</div>
				</div><!-- /.modal-content -->
	  		</div><!-- /.modal-dialog -->
		</div><!-- /.modal -->
	}
}

@{
	@*
	1172 - ID for the slider folder
	var vSliderImage = Umbraco.Content(1172).Children.Where("visible");
	Can only have one slider folder - removed homepage permission from being able to create slider folder
	*@

	var vSliderImage = CurrentPage.Site().Descendants("sliderImages").Where("!sliderHide");
	var imageCount = 0;
	
	System.Text.StringBuilder htmlNode = new System.Text.StringBuilder();
	System.Text.StringBuilder captionNode = new System.Text.StringBuilder();
}

<div class="container-fluid" style="border-top: 5px solid #631d76">
	<div class="row">
		<div class="divSlider">
			<div class="col-xs-12 mainSlider">
				@* Start populating slick slider *@
				@foreach(var img in vSliderImage)
				{
					htmlNode.AppendLine("<div>");
					htmlNode.AppendFormat("	<img src='{0}' alt='{1}' />", Umbraco.TypedMedia(img.sliderImage).Url, Umbraco.TypedMedia(img.sliderImage).Name).AppendLine();
					
					if(img.HasValue("sliderCaptionTitle"))
					{
						captionNode.AppendLine("						<div class='slider-caption'>");
						captionNode.AppendFormat("							<h3>{0}</h3>", img.sliderCaptionTitle).AppendLine();
						captionNode.AppendFormat("							<p>{0}</p>", img.sliderCaption).AppendLine();
						captionNode.AppendLine("						</div>");
						htmlNode.AppendLine(captionNode.ToString());
						captionNode = new System.Text.StringBuilder();
					}

					@* Button - Default value - Learn More *@
					var vButtonText = "Learn More";
					var vURL = "#";

					if(img.HasValue("sliderButtonText"))
					{
						vButtonText = img.sliderButtonText;
					}
					
					@* Get URL - Internal content has priority over external URL *@
					if(img.HasValue("sliderURL"))
					{
						vURL = Umbraco.TypedContent(img.sliderURL).Url;
					}
					else if(img.HasValue("sliderExtURL"))
					{
						vURL = img.sliderExtURL;
					}
					
					htmlNode.AppendFormat("						<a class='applyNow' href='{0}'>{1}</a>", vURL, vButtonText).AppendLine();
					
					htmlNode.AppendLine("</div>");
				}

				@Html.Raw(@htmlNode.ToString())
			</div>
		</div>
	</div>
</div>
<div class="container-fluid text-center">
	@Umbraco.RenderMacro("Navi")
	<div class="container-fluid" style="border-top: 5px solid #631d76"></div>
</div>
<div class="container homepageContent">
	<div class="col-md-8 col-md-offset-2 col-xs-12">
		@Umbraco.Field("bodyText")
	</div>
</div>

	@*
	<div class="row">
		@Html.Raw(@sbLinkBoxes.ToString())
	</div>
	*@
	@Umbraco.RenderMacro("TheCogworksCookieDirective_ShowCookieDirective")

Views/MacroPartials/Include Twitter.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
	<div class="row twitterFeed">
		<p>
			<span class="Heading">Latest Twitter News</span>
		</p>
		<div class="text-center col-xs-12 col-md-8">
			<a id="bcotTwitter" class="twitter-timeline" data-chrome="noheader noscrollbar" data-width="800" data-height="500" href="https://twitter.com/restaurantbcot" >Tweets by The Restaurant at BCoT</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
		</div>
	</div>	
}

Views/MacroPartials/Navi.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

<!-- Navigation Menu -->
<div class="row text-center hidden-xs hidden-sm">
	<div class="col-xs-12">
		<div class="oe_wrapper">
			<ul id="oe_menu" class="oe_menu">
				<li class="oe_main_heading">
					@*<a href="~/"><i class="fa fa-home homeButton" aria-hidden="true"></i></a>*@
					<a href="~/">Home</a>
				</li>
			@{
				@*
					Get contents where isNavigation is True
				*@
				var selection = CurrentPage.Site().Children().Where("isNavigation");
				var count = 1;

				foreach(var item in selection){
					var vMainURL = item.Url;
					if(item.HasValue("redirect"))
					{
						vMainURL = Umbraco.TypedContent(item.redirect).Url;
					}
					
					<li class="oe_main_heading">
						<a href="@vMainURL">@item.Name</a>
					@if(@item.Children().Where("isNavigation").Count() > 0)
					{
						@*
							Create a class base on the Nth menu for sub menu - variable vID
							The class will be used to determine the positioning and height of the submenu
						*@
						var vID = String.Format("div{0}", count);

						<div class="@vID">
							
							<ul class="oe_full">
								<li>
									<ul id="quin" class="subUl">
									
									@if(item.isDepartmentMenu)
									{
										<!-- Display the options for listing courses -->
										<li>
											<a href="/course-list?listtype=A-Z" >A - Z</a>
										</li>
										<li>
											<a href="/course-list?listtype=FT" >Full Time</a>
										</li>
										<li>
											<a href="/course-list?listtype=PT" >Part Time</a>
										</li>
										<li>
											<a href="/course-list?listtype=HE" >Higher Education</a>
										</li>
										<li>
											<a href="/course-list?listtype=APPRENTICE" >Apprenticeships</a>
										</li>
									}
									
									@foreach(var sub in @item.Children().Where("isNavigation"))
									{
										@*
											Page URL = vURL
											Destination is supposed to be URL from content picker should the user prefer to redirect to another page
											Could easily add a text box for custom URL
											* Destination is not yet set in document type
										*@
										var vURL = sub.Url;

										if(sub.HasValue("redirect"))
										{
											vURL = Umbraco.TypedContent(sub.redirect).Url;
										}
										
										@*
											Thumbnails to display as button background
											Thumbnails from standard properties
											Use GetCropUrl on the media picker to get the resized thumbnail of the image
										*@
										string strLink = String.Empty;

										if(sub.HasValue("thumbnail"))
										{											
											var vThumbnail = @Umbraco.Media(sub.thumbnail).GetCropUrl("wideThumbnail");
											strLink = String.Format("<a style=\"background: url({0})\" href=\"{1}\">{2}</a>", vThumbnail, vURL, sub.Name);
										}
										else
										{
											strLink = String.Format("<a href=\"{0}\">{1}</a>", vURL, sub.Name);
										}											
											
										<li>
											@Html.Raw(strLink)
										</li>
									}
									</ul>
								</li>
							</ul>
						</div>
					}
					</li>
						
					count++;
				}
			}
				<li class="oe_main_heading">
					<a href="http://www.bcot.ac.uk">Study at BCoT</a>
				</li>
			</ul>
		</div>
	</div>
</div>

Views/MacroPartials/NaviCss.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
	@*
		Styles for navigation submenu CSS
		Getting the height and left positioning from the content property
		The left positioning is just so that the submenu will always be positioned in the middle of the main menu
	*@
	var menuCSS = CurrentPage.Site().Children().Where("isNavigation");
	var countCSS = 1;
	
	System.Text.StringBuilder htmlNavigationCSS = new System.Text.StringBuilder();
	htmlNavigationCSS.AppendLine("<style type=\"text/css\">");
	
	foreach(var item in menuCSS){
		var vHeight = item.submenuHeight;
		var vLeft = item.submenuLeft;
		
		if(@item.Children.Count() > 1)
		{
			htmlNavigationCSS.AppendFormat("	.div{0}", countCSS).AppendLine();
			htmlNavigationCSS.AppendLine("	{");
			htmlNavigationCSS.AppendFormat("		left: {0}px;", vLeft).AppendLine();
			htmlNavigationCSS.AppendFormat("		height: {0}px;", vHeight).AppendLine();
			htmlNavigationCSS.AppendLine("	}");
		}
		
		countCSS++;
	}
	
	htmlNavigationCSS.AppendLine("</style>");
	@Html.Raw(htmlNavigationCSS.ToString());
}

Views/MacroPartials/ResmioBooking.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
	<div id="resmio-the-restaurant-bcot"></div>
	<script>(function(d, s) { var js, rjs = d.getElementsByTagName(s)[0]; js = d.createElement(s); js.src = "//static.resmio.com/static/en-gb/widget.js#id=the-restaurant-bcot&amp;width=275px&amp;height=400px"; rjs.parentNode.insertBefore(js, rjs); }(document, "script")); </script>
}

Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@Html.Raw(Model.value)

Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))